name: CI/CD Pipeline

on:
  workflow_dispatch:  # 手動実行ボタンを追加
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  analysis-codes:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' # Specify your desired .NET version

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build and run code analysis
      run: dotnet build --no-restore -warnaserror -clp:NoSummary

  build-and-test:
    runs-on: windows-latest
    needs: analysis-codes    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' # 使用している.NETバージョンに合わせて調整
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false

  # アプリケーションのビルドとアーティファクトの作成
  build-artifacts:
    needs: build-and-test
    runs-on: windows-latest
    # if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish application
      run: dotnet publish -c Release -o ./publish --self-contained false
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wpf-application
        path: ./publish/
        retention-days: 30
